# Generated by Django 4.1.1 on 2022-09-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='coin_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
